title: Michael Hall-Snyder 
description: Resume 2021
author:michael.hallsnyder@gmail.com
#show_excerpts: true


theme: minima

header_pages:
  - _posts/ballast.md
  - _posts/disconnect.md
  - _posts/robot.md
  - _posts/gyro.md
  - _posts/launch.md
  - _posts/3dprint.md
  
include:
    - _posts
  

