title: Michael Hall-Snyder 
description:
author: 
minima:
  date_format: "%b %-d, %Y"
  social_links:
     linkedin: Michael Hall-Snyder 
theme: minima

header_pages:
  - _pages/frontpage.md
  - _pages/Contact.md
  - _pages/projects.md

include:
    - _pages
