title: Michael Hall-Snyder 
description:
author: "Michael Hall-Snyder"

social_links:
  linkedin: Michael Hall-Snyder 
theme: minima

header_pages:
  - _pages/frontpage.md
  - _pages/Contact.md
  - _pages/projects.md

include:
    - _pages
